name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - '.github/workflows/android-build.yml'
      - 'Documentation/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android Player
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json', 'Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Unity - Build Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          allowDirtyBuild: true
          buildsPath: Builds

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: Builds
