name: Android Debug APK

on:
  workflow_dispatch:

jobs:
  build-android-debug-apk:
    name: Build Android Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json', 'Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Unity - Build Android Debug APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          buildMethod: CI.BuildAndroidDebug.PerformBuild

      - name: Upload Android debug APK
        uses: actions/upload-artifact@v4
        with:
          name: amazas-debug.apk
          path: Build/Android/amazas-debug.apk
